Repository broadinstitute/gnomad-blog, pull requests merged in 2021-08, with the labels that each got.

#35 Create Changelog “2021-08-rename-filter-in-mitochondria-dataset-and-minor-format-changes”
  content/changelog/2021-08-rename-filter-in-mitochondria-dataset-and-minor-format-changes.md
Labels: netlify-cms/draft

#36 Create Changelog “2021-08-gnomad-hosted-public-files-moved-to-requester-pays-bucket”
  content/changelog/2021-08-gnomad-hosted-public-files-moved-to-requester-pays-bucket.md
Labels: netlify-cms/pending_review

#34 Create Post “2021-07-variant-co-occurrence-phasing-information-in-gnomad”
  content/posts/2021-07-variant-co-occurrence-phasing-information-in-gnomad.md
  src/styles/global.css
Labels: netlify-cms/pending_publish
